name: donation
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_button: ^0.2.0
  animated_text_kit: ^4.2.2
  avatar_glow: ^2.0.2
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  liquid_progress_indicator: ^0.4.0
  liquid_progress_indicator_v2: ^0.5.0
  lottie: ^2.4.0
  rive: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true



  assets:
    - assets/bus.svg
    - assets/lottie_bus.json
    - assets/car.flr
    - assets/bus_anime.flr
